### ISSUE TITLE
Add support for Route 53 Resolver Query Logging 

### ISSUE THREAD

**Issue by Anapo14** [awslabs/assisted-log-enabler-for-aws#1]
Similar to the other logging types, it'd be great to have support for [R53 Resolver query logging](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-query-logs.html), since customers typically like to view VPC flow logs and their DNS logs in tandem.

**Comment by hackersifu** [comment]
@Anapo14 Thanks for adding this! I'll be working on this for the next release and will keep you updated here.

**Comment by hackersifu** [comment]
@Anapo14 Thanks again for creating the issue. I've updated the code to include R53 Resolver Query Logging. Currently, it's only for single account mode, need to finish some tests for the multi account mode before releasing. Plan is for next week sometime.

**Comment by hackersifu** [comment]
@Anapo14 Once again, thanks for creating this issue. I've added support in the multi-account mode for R53 Resolver Query Logging as well in v1.1.1. As such, I'll be closing out this issue.
