### ISSUE TITLE
Feature Request: need a --dry-run option

### ISSUE THREAD

**Issue by jogarzon** [awslabs/assisted-log-enabler-for-aws#20]
To check what would be done without actually making any changes.

**Comment by hackersifu** [comment]
Thanks for submitting this issue, I'll look to get this into one of the releases we have coming out in the next few weeks. I'll update the issue with our progress.

**Comment by hackersifu** [comment]
Dry Run modes have been added for both single & multi-account versions for release 1.4.0 of Assisted Log Enabler for AWS. You can use Dry Run by following these commands: 

```
# Single Account Dry Run
python3 assisted_log_enabler.py --mode dryrun --single_account
# Multi-Account Dry Run
python3 assisted_log_enabler.py --mode dryrun --single_account
```
https://github.com/awslabs/assisted-log-enabler-for-aws#new-dry-run-mode

Release: https://github.com/awslabs/assisted-log-enabler-for-aws/releases/tag/v1.4.0

Thanks again for publishing this issue @jogarzon, please let us know if there's any additional feedback or requests you may have.
