### ISSUE TITLE
Feature Request: Add support for load balancer access logs

### ISSUE THREAD

**Issue by ryanwsmith** [awslabs/assisted-log-enabler-for-aws#3]
https://docs.aws.amazon.com/elasticloadbalancing/index.html

In priority:
- ALB
- ELB (Classic)
- NLB

This will require logging to cloudwatch, which is a good initial target, no need in the short term to enable logging to S3

**Comment by hackersifu** [comment]
Addressing this in the upcoming release.

**Comment by hackersifu** [comment]
Pushed back due to the ALB requirement of having logs in an S3 bucket within the same region as the ALBs.

**Comment by mtoftum** [comment]
I think you'd probably also want to put the log bucket in the same region as the loadbalancer for NLB and ELB.

**Comment by hackersifu** [comment]
> I think you'd probably also want to put the log bucket in the same region as the loadbalancer for NLB and ELB.

Absolutely, all the LB types will require this pattern. The code for each LB type will use dedicated buckets for LB logs. Now that we've added the ability to pick which service to enable (VPC, Route 53, etc), we're working on moving forward with this code, as we won't have to create a bucket per region for customers who don't want to enable LB logging.

**Comment by mtoftum** [comment]
Just to clarify: is that one bucket in each region with load balancers or one bucket in all aws regions?
This might lead to another feature request around limiting regions in action.

**Comment by hackersifu** [comment]
> Just to clarify: is that one bucket in each region with load balancers or one bucket in all aws regions?
> This might lead to another feature request around limiting regions in action.

Great point, we'll look to add the functionality to only create buckets in regions where load balancers exist, to prevent creating buckets in regions where there are no logs to collect.

**Comment by cydneystude** [comment]
ELB logs added 4/18
