### ISSUE TITLE
Enable ability to use preexisting S3 bucket

### ISSUE THREAD

**Issue by hackersifu** [awslabs/assisted-log-enabler-for-aws#37]
Provide the ability within the Assisted Log Enabler for AWS to use a preexisting S3 bucket for storing the logs.

**Comment by Outrun207** [comment]
Hello have you made progress on this issue? Otherwise I would pick it up

**Comment by hackersifu** [comment]
> Hello have you made progress on this issue? Otherwise I would pick it up

I have not! However, feel free to pick it up as you stated. Pinging @cydneystude as well.

**Comment by ayankowsky** [comment]
Feature added in latest release.
